#!/bin/sh

cat <<EOF > .env
APP_NAME=Cannabs2Go
APP_ENV=local
APP_VERSION=0.1.7
APP_KEY=base64:niKVlM4IFQ3JK+pkBJSG5FO/8sC4PtEtYYiR8V0OgRo=
APP_DEBUG=true
APP_URL=https://cannabs2go.com
LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST_READ=
DB_HOST_WRITE=
DB_PORT=3306
DB_DATABASE=
DB_USERNAME=
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=4320
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=mailgun
MAIL_HOST=email-smtp.us-west-2.amazonaws.com
MAIL_PORT=2525
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=null

SHOP_MAIL_FROM=noreply@cannabs2go.com
ADMIN_MAIL_TO=atendimento@cannabs2go.com

fixer_api_key=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

ALGOLIA_APP_ID=
ALGOLIA_SECRET=

SES_KEY=
SES_KEY_SECRET=
SES_REGION=us-west-2

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=sa-east-1
AWS_BUCKET=purecaps
AWS_URL=

MAILGUN_DOMAIN=
MAILGUN_SECRET=4
EOF
